//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QuizdbEntities : DbContext
    {
        public QuizdbEntities()
            : base("name=QuizdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<onlineexam> onlineexams { get; set; }
        public virtual DbSet<AdminUser> AdminUsers { get; set; }
    
        public virtual ObjectResult<quizonline_Result> quizonline()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<quizonline_Result>("quizonline");
        }
    }
}
